// Generated by CoffeeScript 1.9.1
var document;

document = (function(_this) {
  return function(arg) {
    var baseUrl, bundle, error, http, success;
    baseUrl = arg.baseUrl, http = arg.http, bundle = arg.bundle, success = arg.success, error = arg.error;
    return http({
      method: 'POST',
      url: baseUrl + '/Document',
      data: bundle,
      success: success,
      error: error
    });
  };
})(this);

module.exports = document;
