// Generated by CoffeeScript 1.9.1
var buildParams, history, historyAll, historyType;

buildParams = function(count, since) {
  var prm;
  prm = {};
  if (since != null) {
    prm._since = since;
  }
  if (count != null) {
    prm._count = count;
  }
  return prm;
};

history = function(arg) {
  var baseUrl, count, error, http, id, since, success, type;
  baseUrl = arg.baseUrl, http = arg.http, type = arg.type, id = arg.id, success = arg.success, error = arg.error, count = arg.count, since = arg.since;
  return http({
    method: 'GET',
    url: baseUrl + "/" + type + "/" + id + "/_history",
    params: buildParams(count, since),
    success: success,
    error: error
  });
};

historyType = function(arg) {
  var baseUrl, count, error, http, since, success, type;
  baseUrl = arg.baseUrl, http = arg.http, type = arg.type, success = arg.success, error = arg.error, count = arg.count, since = arg.since;
  return http({
    method: 'GET',
    url: baseUrl + "/" + type + "/_history",
    params: buildParams(count, since),
    success: success,
    error: error
  });
};

historyAll = function(arg) {
  var baseUrl, count, error, http, since, success;
  baseUrl = arg.baseUrl, http = arg.http, success = arg.success, error = arg.error, count = arg.count, since = arg.since;
  return http({
    method: 'GET',
    url: baseUrl + "/_history",
    params: buildParams(count, since),
    success: success,
    error: error
  });
};

module.exports = function(q) {
  if ((q.id != null) && (q.type != null)) {
    return history(q);
  } else if (q.type != null) {
    return historyType(q);
  } else {
    return historyAll(q);
  }
};
