// Generated by CoffeeScript 1.9.1
var doGet, getRel, queryBuider, search;

queryBuider = require('./query');

doGet = function(http, uri, success, error) {
  return http({
    method: 'GET',
    url: uri,
    success: success || function() {},
    error: error || function() {}
  });
};

search = (function(_this) {
  return function(arg) {
    var baseUrl, error, http, query, queryStr, success, type, uri;
    baseUrl = arg.baseUrl, http = arg.http, type = arg.type, query = arg.query, success = arg.success, error = arg.error;
    queryStr = queryBuider.query(query);
    uri = baseUrl + "/" + type + "/_search?" + queryStr;
    return doGet(http, uri, success, error);
  };
})(this);

getRel = function(rel) {
  return function(arg) {
    var baseUrl, bundle, error, http, l, success, urls;
    baseUrl = arg.baseUrl, http = arg.http, bundle = arg.bundle, success = arg.success, error = arg.error;
    urls = (function() {
      var i, len, ref, results;
      ref = bundle != null ? bundle.link : void 0;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        l = ref[i];
        if (l.rel === rel) {
          results.push(l.href);
        }
      }
      return results;
    })();
    if (urls.length !== 1) {
      return error("No " + rel + " link found in bundle");
    } else {
      return doGet(http, urls[0], success, error);
    }
  };
};

module.exports.search = search;

module.exports.next = getRel("next");

module.exports.prev = getRel("prev");
