// Generated by CoffeeScript 1.9.1
var wrap;

wrap = function(cfg, fn, middlewares) {
  var next;
  if (typeof middlewares === 'function') {
    middlewares = [middlewares];
  }
  next = function(wrapped, nextf) {
    return nextf(cfg, wrapped);
  };
  return [].concat(middlewares || []).reverse().reduce(next, fn);
};

module.exports = wrap;
